### ISSUE TITLE
v1.4 vs v.2x

### ISSUE THREAD

**Issue by magma1447** [Surfoo/oauth2-geocaching#3]
Hi.

Project-GC switched from its own oauth implementation to this a few years ago. As you probably know Geocaching.com is making several oAuth changes on the 1st of January 2024. Staging is already updated to that.

Since Project-GC is still using PHP 7.x and it's a major work task to upgrade to 8.x, and might even cause other issues, so you know if your 1.4 oauth version works with the coming changes?

I tried to update my code to authenticate against Staging to verify, but I am this far only getting a http code 500 on their end. Sadly I don't know if I missed changing something in my end or it's because oauth2-geocaching v1.4 is too old. It would have been wise if I tested it before they updated Staging as well.

**Comment by magma1447** [comment]
It seems to work. I managed to find an issue in my code when I switched to staging.

**Comment by Surfoo** [comment]
Hello Magnus,
Is the version 2.0 works well on your side with PHP 7.x ? (which one btw?) 
Because in the composer.json, PHP version is >=8.1 :thinking:

**Comment by verfriemelt-dot-org** [comment]
heyho, i am currently also migrating towards oauth 2 with a php application and get just 500's on groundspeaks site after confirming a login with the demo setup here as well :thinking: 

so @magma1447 was this something oauth related that you changed here?

**Comment by magma1447** [comment]
> Hello Magnus, Is the version 2.0 works well on your side with PHP 7.x ? (which one btw?) Because in the composer.json, PHP version is >=8.1 🤔

No I didn't try 2.x, I noticed the dependency. I am sticking to version 1.4, and that one works with Staging, so I assume it will work with production next year as well.

**Comment by magma1447** [comment]
> heyho, i am currently also migrating towards oauth 2 with a php application and get just 500's on groundspeaks site after confirming a login with the demo setup here as well 🤔
> 
> so @magma1447 was this something oauth related that you changed here?

The mistake I did that caused http code 500 was that I used the wrong keys. Not all of my code used the correct keys after switching.

**Comment by verfriemelt-dot-org** [comment]
mhmm, okay. so just to rule out some issues on my side, i just tried the demo code by adding the clientid and secret, and i'll always end up in a 500 :thinking:

**Comment by verfriemelt-dot-org** [comment]
i found the issue, for some reason my http://localhost:8081 seems to be an invalid redirect uri. i'll get in touch with groundspeak about that.

**Comment by magma1447** [comment]
> i found the issue, for some reason my http://localhost:8081 seems to be an invalid redirect uri. i'll get in touch with groundspeak about that.

Your callback url must be whitelisted in their end. I have a couple for my site.

**Comment by verfriemelt-dot-org** [comment]
yeah, i let them add a couple this morning. but there seems to be something off with that.

**Comment by Surfoo** [comment]
I just released a new version 1.4.1 with the update from the 2.0 and compatible with PHP >=7.3

**Comment by magma1447** [comment]
> I just released a new version 1.4.1 with the update from the 2.0 and compatible with PHP >=7.3

Thank you! I will have to make sure to look into upgrading to PHP 8 next year. I have some plans that will make that part easier in the future.

**Comment by magma1447** [comment]
1.4.1 broke Project-GC's authentication. And I was stupid enough to just upgrade and didn't test it.

I haven't figured out why yet. This throws an exception:
```
		$tokenObject = $provider->getAccessToken('authorization_code', [
			'code' => $_GET['code'],
		]);
```

And the message I get is Internal server error. My problem is that I was supposed to make dinner a while ago, so now when I learned that a downgrade solved my immediate issues I will have to go back and do that.

**Comment by Surfoo** [comment]
Oh ****, I'm sorry, I made a mistake in the tag name...
You can look at the diff in `demo/index.php` here: https://github.com/Surfoo/oauth2-geocaching/compare/1.4.0...1.4.1 
It's simpler and with less code about PKCE (integrated into `league/oauth2-client`)

**Comment by magma1447** [comment]
> Oh ****, I'm sorry, I made a mistake in the tag name... You can look at the diff in `demo/index.php` here: [1.4.0...1.4.1](https://github.com/Surfoo/oauth2-geocaching/compare/1.4.0...1.4.1) It's simpler and with less code about PKCE (integrated into `league/oauth2-client`)

No worries. I have patched up the code in my end. It works against Staging, hopefully it will work against Production in two months as well.
